example_wordcloud: HTMLPage Class Reference
HTMLPage Class Reference
Static Public Member Functions
static String startPage (int numSizes, int startSize, int increment)
static String endPage ()
static String formatWord (String word, int cssSize)
static String formatWord (Entry< String, Integer > wordCount)
Detailed Description
A simple module to encapsulate using HTML tags.
Note, makes use of CSS styling in an effort ease changing the style later.
Author
Robert C. Duvall
Definition at line 12 of file HTMLPage.java.
Member Function Documentation
static String HTMLPage.endPage () static
Returns
tags to be included at bottom of HTML page
Definition at line 27 of file HTMLPage.java.
Referenced by TagCloud.toString().
static String HTMLPage.formatWord (String word, int cssSize) static
Returns
tags to display a single styled word
Definition at line 34 of file HTMLPage.java.
Referenced by formatWord(), and TagCloud.toString().
static String HTMLPage.formatWord (Entry< String, Integer > wordCount) static
Returns
tags to display a single styled word
Definition at line 41 of file HTMLPage.java.
References formatWord().
static String HTMLPage.startPage (int numSizes, int startSize, int increment) static
Returns
tags to be included at top of HTML page
Definition at line 16 of file HTMLPage.java.
Referenced by TagCloud.toString().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/example_wordcloud/repository/src/HTMLPage.java