example_wordcloud: TagCloud Class Reference
TagCloud Class Reference
Public Member Functions
TagCloud (Scanner ignoreWords)
void makeCloud (Scanner input, int numWordsToKeep, int groupSize)
String toString ()
Static Public Member Functions
static void main (String[] args)
Private Member Functions
List< Entry< String, Integer > > countWords (Scanner input)
List< Entry< String, Integer > > topWords (List< Entry< String, Integer >> tagWords, int numWordsToKeep, int groupSize)
boolean isTaggable (String word)
List< String > readWords (Scanner input)
Static Private Member Functions
static String sanitize (String word)
Private Attributes
Set< String > myCommonWords
List< Entry< String, Integer > > myTagWords
Static Private Attributes
static final int DEFAULT_NUM_GROUPS = 20
static final int DEFAULT_MIN_FONT = 6
static final int DEFAULT_INCREMENT = 4
static final String DEFAULT_IGNORE_FILE = "common.txt"
static final String PUNCTUATION = "[\\d\\p{Punct}]+"
static final String END_OF_FILE = "\\Z"
static final String WHITESPACE = "\\s"
Detailed Description
A visual representation for the number of times various words occur in a given document.
In a tag cloud, the most common English words are usually ignored (e.g. the, a, of), since they do not give any useful information about the topic of the document being visualized.
Author
Robert C Duvall
Christopher La Pilla
Definition at line 26 of file TagCloud.java.
Constructor & Destructor Documentation
TagCloud.TagCloud (Scanner ignoreWords)
Constructs an empty TagCloud.
Definition at line 46 of file TagCloud.java.
References readWords().
Referenced by main().
Member Function Documentation
List<Entry<String, Integer> > TagCloud.countWords (Scanner input) private
Definition at line 76 of file TagCloud.java.
References isTaggable(), and readWords().
Referenced by makeCloud().
boolean TagCloud.isTaggable (String word) private
Definition at line 104 of file TagCloud.java.
Referenced by countWords().
static void TagCloud.main (String[] args) static
Definition at line 123 of file TagCloud.java.
References DEFAULT_NUM_GROUPS, makeCloud(), and TagCloud().
void TagCloud.makeCloud (Scanner input, int numWordsToKeep, int groupSize)
Create a word cloud from the given input.
Definition at line 56 of file TagCloud.java.
References countWords(), and topWords().
Referenced by main().
List<String> TagCloud.readWords (Scanner input) private
Definition at line 116 of file TagCloud.java.
References sanitize().
Referenced by countWords(), and TagCloud().
static String TagCloud.sanitize (String word) static private
Definition at line 109 of file TagCloud.java.
Referenced by readWords().
List<Entry<String, Integer> > TagCloud.topWords (List< Entry< String, Integer >> tagWords, int numWordsToKeep, int groupSize) private
Definition at line 87 of file TagCloud.java.
Referenced by makeCloud().
String TagCloud.toString ()
Convert each word to appropriately sized font based on its frequency.
Definition at line 64 of file TagCloud.java.
References HTMLPage.endPage(), HTMLPage.formatWord(), and HTMLPage.startPage().
Member Data Documentation
final String TagCloud.DEFAULT_IGNORE_FILE = "common.txt" static private
Definition at line 31 of file TagCloud.java.
final int TagCloud.DEFAULT_INCREMENT = 4 static private
Definition at line 30 of file TagCloud.java.
final int TagCloud.DEFAULT_MIN_FONT = 6 static private
Definition at line 29 of file TagCloud.java.
final int TagCloud.DEFAULT_NUM_GROUPS = 20 static private
Definition at line 28 of file TagCloud.java.
Referenced by main().
final String TagCloud.END_OF_FILE = "\\Z" static private
Definition at line 34 of file TagCloud.java.
Set<String> TagCloud.myCommonWords private
Definition at line 38 of file TagCloud.java.
List<Entry<String, Integer> > TagCloud.myTagWords private
Definition at line 40 of file TagCloud.java.
final String TagCloud.PUNCTUATION = "[\\d\\p{Punct}]+" static private
Definition at line 33 of file TagCloud.java.
final String TagCloud.WHITESPACE = "\\s" static private
Definition at line 35 of file TagCloud.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/example_wordcloud/repository/src/TagCloud.java